   fprintf (fp, "# Generated by Wget on %s.\n", datetime_str (&cookies_now));
   fputs ("# Edit at your own risk.\n\n", fp);
 
-  hash_table_map (jar->chains, save_cookies_mapper, fp);
-
+  for (hash_table_iterate (jar->chains, &iter);
+       hash_table_iter_next (&iter);
+       )
+    {
+      const char *domain = iter.key;
+      struct cookie *cookie = iter.value;
+      for (; cookie; cookie = cookie->next)
+	{
+	  if (!cookie->permanent && !opt.keep_session_cookies)
+	    continue;
+	  if (cookie_expired_p (cookie))
+	    continue;
+	  if (!cookie->domain_exact)
+	    fputc ('.', fp);
+	  fputs (domain, fp);
+	  if (cookie->port != PORT_ANY)
+	    fprintf (fp, ":%d", cookie->port);
+	  fprintf (fp, "\t%s\t%s\t%s\t%.0f\t%s\t%s\n",
+		   cookie->domain_exact ? "FALSE" : "TRUE",
+		   cookie->path, cookie->secure ? "TRUE" : "FALSE",
+		   (double)cookie->expiry_time,
+		   cookie->attr, cookie->value);
+	  if (ferror (fp))
+	    goto out;
+	}
+    }
+ out:
   if (ferror (fp))
     logprintf (LOG_NOTQUIET, _("Error writing to `%s': %s\n"),
 	       file, strerror (errno));
