	getMyHostname());
    if (!log_errors)
	return tmp_error_buf;
    return tmp_error_buf;
}


#define CACHED_REQUEST_ERROR_MSG "\
<TITLE>ERROR: Invalid HTTP Request</TITLE>\n\
<H2>Invalid HTTP Request</H2>\n\
<HR>\n\
<PRE>\n\
%s\n\
</PRE>\n\
<HR>\n\
<ADDRESS>\n\
Generated by cached/%s@%s\n\
</ADDRESS>\n\
\n"

char *cached_error_request(request, type, address)
     char *request;
     int type;
     char *address;
{
    int index;

    tmp_error_buf[0] = '\0';
    if (type == ERR_MIN || type > ERR_MAX)
	fatal_dump("cached_error_url: type out of range.");
    index = (int) (type - ERR_MIN);

    sprintf(tmp_error_buf, CACHED_REQUEST_ERROR_MSG,
	request,
	SQUID_VERSION,
	getMyHostname());
    if (!log_errors)
	return tmp_error_buf;
    return tmp_error_buf;
}
